### ISSUE TITLE
Improve wording of activation email and that sends out request other user emails 

### ISSUE THREAD

**Issue by stefanw** [okfde/froide#183]
When users activate accounts pending requests are sent out. Improve wording or make this a 2-step process in order to avoid sending out requests that were written with the user's email address but not by the user.

**Comment by arnese** [comment]
Instead of
"This is an email from {{ site_name }} to confirm your email address.
Please visit the link below:"

"A request has been sent via {{ site_name }}.
If you are the sender of the request, please confirm your email address and request by visiting the link below:
{{ url }}

If you are not the sender of the request, you can ignore this email.

**Comment by arnese** [comment]
Text for German emails here: https://docs.google.com/spreadsheets/d/1XY7ESlINg_8mC83qs4IQprqFFdmq41L0VdQ_YLVVen0/edit?pli=1#gid=0

**Comment by arnese** [comment]
Additionally emails to users notifiying them of changes should not only include title, but also authority the request was sent to.
For example, https://github.com/stefanw/froide/blob/master/froide/foirequest/templates/foirequest/emails/became_asleep.txt should start with 
" Your request "{{ title }}" to "{{ authority }}" is not marked " ...

**Comment by arnese** [comment]
E-Mails could include an additional header to group emails to one request. For example, Github sends out emails like:
```In-Reply-To: <FreifunkBremen/yanic/pull/65@github.com>
References: <FreifunkBremen/yanic/pull/65@github.com>
```
