### ISSUE TITLE
Move of froide GitHub repo to facilitate further development

### ISSUE THREAD

**Issue by pdehaye** [okfde/froide#209]
There is discussion to slightly repurpose Froide for different goals. 

One goal could be a [Personal Data request service](https://github.com/okfn/ideas/issues/92) (suggested by me), and another could be an [IsItOpenData reboot](https://github.com/okfn/ideas/issues/41) (suggested by @rgrp). 

The dynamics required have lots of commonality, putting the interaction with the entity holding data itself in the commons (after stripping some information due to privacy concerns). In the personal data case, the substance of the response should be treated with special care (and most likely not shown publicly), as it really is private data. 

Codewise, it would make sense to implement some more modular system in Froide dictating the interaction. To support collaborative development towards this, I suggest the following moves:
 -  https://github.com/stefanw/froide -> https://github.com/okfn/froide
 -  https://github.com/okfde/froide-theme -> https://github.com/okfn/froide-theme

(this would help for access control, fundraising, visibility, code development, discussions around code development, etc)

**Comment by stefanw** [comment]
Hi @pdehaye,

I'm all for making froide more modular and encourage more use. Moving this repo to a GitHub organisation is a good first step. However, I don't see any advantage moving repos to the `okfn` organisation over the `okfde` organisation, so I'm going to move them to the `okfde` organisation (simply because I'm an admin there).

I will add you as a collaborator on this repository. Let's discuss how to make froide more modular in there.

**Comment by pdehaye** [comment]
Great, thanks!

**Comment by stefanw** [comment]
Repository is moved, you have write access. Please contribute through PRs with a plan.

We don't necessarily need backward compatibility but we do need migration plans for existing instances running `froide`. So for any changes we should start a `CHANGELOG` etc.

**Comment by rgrp** [comment]
😄  👏
