### ISSUE TITLE
Crowdfunding module

### ISSUE THREAD

**Issue by arnese** [okfde/froide#232]
It should be possible to crowdfund for
- Lawsuits
- Fees

This would be an option for users on request. Money should probably go to FragDenStaat to be forwarded.

**Comment by GiantCrocodile** [comment]
Nice idea as it is likely to be needed for nice but expensive FOIA requests/suings.

**Comment by jfilter** [comment]
💯👌. Should have top priority in my opinion.

**Comment by GiantCrocodile** [comment]
I see a problem regarding `Money should probably go to FragDenStaat to be forwarded.`: taxation and related proofs/evidences for the money you get but on bank accounts of FragDenStaat.de. Would the donations related tax stuff be done by FragDenStaat.de?

**Comment by arnese** [comment]
It would. But we would have to sort it out with our lawyers. Other option would be to have the money go to the user directly but this would create other problems of trust and tax stuff as well.

**Comment by GiantCrocodile** [comment]
I don't see a real issue of taxation stuff if the money goes to an user. The user can do the tax declaration easily him/herself and it would be less difficult than the taxation done by FragDenStaat for third parties (users). I'm not even sure who is guilty for it at the end: the user who was asking for the donations because it is used for his stuff (suing/paying fees) or if FragDenStaat.de is liable because they do it in their name. It could also be relevant to keep in mind who pays higher taxes on the donations: user or FragDenStaat.de.

**Comment by arnese** [comment]
Maybe at least in Germany the betterplace API is an option?
It's documented her: https://github.com/betterplace/betterplace_apidocs/blob/master/donation_form/third_party_app_donation_form.md

**Comment by arnese** [comment]
We have implemented a first version which is available to moderators at the moment. One example is to be seen here: https://fragdenstaat.de/crowdfunding/campaign/unterausschuss-mobilitat-am-272019-nicht-offentlich/
