### ISSUE TITLE
Changing privacy settings after account creation

### ISSUE THREAD

**Issue by LukeLR** [okfde/froide#310]
When I reviewed my account settings on Fragdenstaat.de today, I stumbled upon the privacy section. It just reads something like "Your name is displayed publicly".

It seems like I didn't opt out of real name display during account creation. As this happened on mistake, I tried to change that setting, but I couldn't find an option. Therefore, I needed to delete my account and create a new one in order to change this setting.

It shouldn't be that complicated. Users should be able to change their usernames after account creation. Opting in for real name display shouldn't be binding for all time afterwards.

Please provide an option to change the privacy setting on the profile settings page.

**Comment by stefanw** [comment]
Redaction happens automatically at the point of receiving text from the outside. That's why it's not an option you can toggle back and forth, because users would be confused about their requests being redacted in some parts and not in others because they changed their settings.

Currently, we can change the privacy setting for users from public to private on request. This involves a background task that goes through all existing correspondence and applies redaction as needed. This step cannot be undone.

We probably could provide a one-time use interface to make the account private.

**Comment by arnese** [comment]
Setting an account to private is possible now.
