### ISSUE TITLE
Disable HTML emails (with a user preference)

### ISSUE THREAD

**Issue by jfilter** [okfde/froide#338]
Disable HTML emails (with a user preference)

**Comment by stefanw** [comment]
This should be – and in many email client is – a client-side preference. Where do you see the harm?

**Comment by jfilter** [comment]
It depends on your level of paranoia, but HTML emails are a security risk. And it's not that easy to disable them client-side. I didn't find a solution for macOS Mail so far. There was a way to disable HTML but it's not working anymore.

```bash
defaults write com.apple.mail PreferPlainText -bool true
```

**Comment by Ryuno-Ki** [comment]
As far as I know, the implementation client-side relies on another tool which converts HTML to plain text (with better or worse results).

What do you do if someone sends HTML-mails only? (Instead of telling their client to send both formats)
- Not showing mail at all?
- Informing, that there is mail, but it can't be displayed?
- Converting HTML to Plain text server-side? (How?)
- …

**Comment by stefanw** [comment]
@Ryuno-Ki I think this issue is about the emails that FragDenStaat has started sending to users. They were text-only but we just started sending text+html emails for some of them (and will expand that to include more).

Regarding emails from public authorities to FragDenStaat, you are right: we convert HTML-only emails to Markdown-like text, mostly just to recover URLs from links. It works well enough except for some HTML (e.g. tables).

@jfilter if you see HTML as a security risk than you should disable it in your client (pretty sure you get more than FDS mails as HTML). If your client does not support that, you should switch clients (e.g. Thunderbird supports it).

**Comment by jfilter** [comment]
> pretty sure you get more than FDS mails as HTML

Yeah, but those emails are not for clicking links. FDS mail are mainly to click on links.

**Comment by stefanw** [comment]
And clicking links actually works better in HTML – unfortunately. We have problems with `@t-online.de` customers where the web mail interface breaks long links which then become unusable. HTML mails fix this.

Opting out would not be too difficult to implement, but it would make our settings interface even more complicated. I will look at this again once we look at notification settings.
