### ISSUE TITLE
Request page redesign

### ISSUE THREAD

**Issue by arnese** [okfde/froide#393]
Alpha page; add ?alpha=1 to request page, for example
https://fragdenstaat.de/anfrage/kaufvertrag-zu-privatisierung-des-bundesanzeiger-verlags-1/?alpha=1

Done:

- [x] Make short link copier work
- [x] Translate
- [x] Fill in lorem ipsum for advice messages
- [x] add admin buttons
- [x] change "1 Nachrichten" to "1 Nachricht"
- [x] Brauchen wir ein Feature "Alle einklappen, alle ausklappen?"
- [x] Bei zu klassifizierenden Anfragen ist man schon im Bearbeitungsmodus (richtig so), aber kriegt dann trotzdem "Bearbeiten" angezeigt statt "zurück" 
- [x] text in collapsed messages is not blacked out
- [x] missing permission check for reply from
- [x] remove Recipient field in message head, when info is not available
- [x] make comments readable for everyone, not just logged in users

Open to do:
- [x] Enable banners - examples [here](https://fragdenstaat.de/anfrage/kontrollbericht-zu-feinkostfleischerei-rohde/), coming from campaigns and [here](https://fragdenstaat.de/anfrage/verstoe-gegen-den-mietendeckel-mietenwog-bln/)
- [x] Enable donation banner in request page
- [x] Enable "Schwärzen" button again
- [x] form for changing sender in message head is buggy (radio button click disfunctional) and not well styled
- [x] Guidance: JS-code for adding snippet to reply 
- [x] Add download buttons "Download as zip" and "Download as PDF"
- [x] Add admin button to individual messages (not just overall page)
- [x] Upload Mail -> received Mail/sent Mail -> form
- [x] Mediation form (under "Other options"-Dropdown)
- [x] Project functions (?)
- [x] Add project link
- [x] Make individual messages linkable (I would suggest the date to be the link like now i.e. https://fragdenstaat.de/anfrage/nachricht-von-guttenberg-auf-handy-der-bundeskanzlerin/#nachricht-549951)
- [x] More help functionalities?
- [x] Add "Erneut senden" button ([like here](https://fragdenstaat.de/anfrage/corona-impfung-2/#nachricht-550480))
- [x] Make Summary editable again after first write-up
- [x] add Prolongue Deadline function
- [x] add "Als Fax versenden" Button
- [x] Add team access
- [x] Add secret URLs
- [x] discuss: make answer field only appear when clicked on or permanent as it is now?
- [ ] new feature? "Was this answer helpful?" and "rate the answer!" or "rate the authority!"
- [x] Sharing-Text statt "$Anfrage-URL" als "Ich habe per #IFG gefragt nach $Anfrage-URL"
- [x] Banner for closed request ([like here](https://fragdenstaat.de/anfrage/welche-hilfen-wurden-italien-in-der-coronia-krise-von-der-eu-geleistet/))
- [x] 2x "Please set a new status" -> extra Tab or next to message maybe?
- [x] "Your request ist overdue, plase act now" -> extra Tab or next to message maybe?
- [x] + mediator form: "You request has been refused. Consider sending a letter to a mediator"; as well as all correspondence with mediator --> new form in extra tab
- [x] "This request is not an FoI request ..."
- [x] "This request has been closed and cannot receive further messages"
- [x] "This request is not public. You clicked a special URL ..."
- [x] "Special access. You clicked a special URL ..."
- [ ] Increase color contrast for menu, "request to" and similar grey instances. For now, contrast is 1:3, should be at least 1:4.5 (like tags text); also color contrast between published and non-published attachment should be higher to distinguish better.
- [ ] Question: Should we make it more distinguishable who sent an email? Users have suggested additional colour coding
- [x] More space between messages?
- [x] Names of attachments visible if there is no text?

**Comment by arnese** [comment]
Small issues with Timeline:

- [ ] Deadline seems to not appear in right order (here: December, but appears after February)
- [ ] It probably makes sense to add year for current year as well, no? (here: add 2020?)
- [ ] I got the feedback that it's not immediately clear that the timeline refers to the messages next to it, but I find it pretty intiuitive that it does, actually. So just ignore?

![timeline](https://user-images.githubusercontent.com/9381889/102504572-4c4cea00-4081-11eb-94ca-2d4ab71b9223.png)

**Comment by gambolputty** [comment]
Referring to " it's not immediately clear that the timeline refers to the messages next to it": I need more feedback on that one. Does the timeline look misplaced or not being part of the rest of the design? Also what would be the alternative? Is the [Discourse](https://forum.okfn.de/t/auswaertiges-amt-schwaerzungen/1170) timeline better?

**Comment by arnese** [comment]
It seems to not look as it's part of the rest of the design because it's in gray while the messages are in white (so that's different to the Discourse timeline). But I don't see it that way, so I am inclined to dismiss that - just wanted you to know in case you see a point there.

**Comment by arnese** [comment]
More feedback regarding attachments: Suggestion to increase shown attachments from 3 to 5 (and then to decrease height of icons, if more space is needed). I am not sure about this. Maybe more feedback from others is needed?
![Screenshot_2020-12-18 Training Material for Return Operations](https://user-images.githubusercontent.com/9381889/102592233-7949dd00-4113-11eb-8fb4-9ec290953244.png)
![Screenshot_2020-12-18 Training Material for Return Operations(1)](https://user-images.githubusercontent.com/9381889/102592234-79e27380-4113-11eb-9fb3-86a5e926b0fe.png)

**Comment by arnese** [comment]
In the old version we have an "Update Status" button next to the newest authority message when you haven't classified a request yet. I guess we won't need this as we will have other way alert people to update their status?
Right now, my user flow with the alpha page is this: I get an email notification about a new response, I click on it and read the response on FDS and then I click it away *without* classifying the response. Usually, I would have clicked on the "Classify status" button.
![Screenshot_2020-12-18 Dienstanweisung zu privaten Sicherheitsdiensten und Abschiebehaft](https://user-images.githubusercontent.com/9381889/102623980-a3b38e80-4143-11eb-8998-fe61bf208e5e.png)

**Comment by gambolputty** [comment]
Referring to the **number of displayed attachment** items on initial load: 

I came up with the number three because it seems to me that the average maximum number of approved attachments on the site is three. If it's not three or less, it's sometimes 8, 10 or even > 20. 

In mails attachments are usually displayed below the message text. But FragDenStaat wants to display the attachments above, because they're of the same priority. So limiting the number of displayed attachments is a compromise of displaying two sections of equal priority.

There's no functionality for switching the limit between mobile and desktop. If there was, I'would still recommend not changing it, because in terms of "completeness" a higher limit doesn't make sense if I'm right about the average number I explained above.

**Comment by gambolputty** [comment]
Referring to  **attachment icon size**: I'm afraid this is not easily doable and it would require to come up with a new draft. Each attachment item consists of three lines (even though only 2 are displayed sometimes). We could make the height of the container including the icons adaptable and them shrink if more space is available. But we don't because of consistency reasons (there's no visual meaning in "small" or  "large" attachments, so we keep them the same size).

**Comment by gambolputty** [comment]
Attachment filename length:

I removed the Django `truncatefilename`-function to truncate the filenames and now we rely on Bootstraps `text-truncate`-class. The result is that the filenames are still truncated but don't display the file extension anymore when there's not enough space. I think, that's OK, because we can now guess the file type by the icon of the attachment and there's still the complete filename + extension showing when you hover the name with the mouse in desktop view. Let me know what you think.

<img width="559" alt="Bildschirmfoto 2020-12-23 um 17 15 41" src="https://user-images.githubusercontent.com/8270488/103016544-7d766000-4542-11eb-8a79-218a54cae2ea.png">
<img width="820" alt="Bildschirmfoto 2020-12-23 um 17 15 59" src="https://user-images.githubusercontent.com/8270488/103016564-8830f500-4542-11eb-88a5-bdab2068029f.png">
<img width="663" alt="Bildschirmfoto 2020-12-23 um 17 16 14" src="https://user-images.githubusercontent.com/8270488/103016587-9121c680-4542-11eb-8fbc-59f2299f6cf6.png">

**Comment by arnese** [comment]
Yes, perfect! The new attachment names are better, I think. Thank you!

**Comment by alehaa** [comment]
It would be nice, if the manual redaction feature could be added to the list of features for the new design, as the old one did provide.

In addition, I miss the color highlighting of messages from the old design, e. g. to simply distinguish messages of agencies from ones related to mediation. As the new design seems to be minimalistic (to me), instead of using a background color for the message body, just a simple colored line on the left side could be used like for selected (unfolded) ones, as seen in the mockup below.
<img width="573" alt="screenshot" src="https://user-images.githubusercontent.com/6250567/103237402-c1ed6b80-4947-11eb-934b-e13795bea14a.png">

**Comment by alehaa** [comment]
I think there's another issue with the design: If a FOI request is linked to another one, it's common to post its link as comment in the related request. The new design hides those links if the related message is collapsed. A new feature (maybe in a new issue?) could be to implement some kind of "related FOI requests" tab, to list those requests.

**Comment by arnese** [comment]
Yes, these hints of relations that used to be part of a comment should be displayed otherwise, for example as part of the summary. Mediation messages from the Commissioners should actually not be displayed in the same thread, but rather in another tab soon.

**Comment by alehaa** [comment]
The new design omits the request text, [if a summary has been defined](https://github.com/okfde/froide/blob/2cdc2db15b1bab74002447b75eeb32f379ffc424/froide/foirequest/templates/foirequest/alpha/header/header.html#L37). Is this intended? Right now one has to open the first message to know what the FOI request is about.

**Comment by arnese** [comment]
Yes, that's intended. Otherwise, the upper part would get too long. And we want to focus more on the results of requests.

**Comment by arnese** [comment]
In cases where there are four attachments, they should all be displayed instead of the usual three plus 1
see here: https://fragdenstaat.de/anfrage/vertrage-mit-genios-pressreader-und-munzinger/#nachricht-595712
![Screenshot_2021-05-13 Verträge mit Genios, Pressreader und Munzinger](https://user-images.githubusercontent.com/9381889/118124390-ccd80280-b3f5-11eb-8a33-d0b95351cf9b.png)
