### ISSUE TITLE
Automatic redaction can leak information

### ISSUE THREAD

**Issue by alehaa** [okfde/froide#437]
If attachments include the name of the requester, these text passages will be redacted automatically. However, if several attachments are combined to a single one and one of them is available publicly, this can be used to leak information about the requester's name.

For example an agency has replied by combining several documents into one. As the first page contains sensitive information, it needs to be redacted. However, if just a single page gets redacted, the whole document gets scanned for the requester's name. Now, if the following pages include a public document (e. g. „Drucksache“ from the german Bundestag), one can match the original with the redacted one and get the requester's name by checking the redacted words.

One could argue, that this wouldn't happen if agencies wouldn't combine documents in the first place. However, as they will do, froide should implement features to avoid this kind of leak. I suggest some kind of "splitting documents" or "undo selected redaction".

**Comment by arnese** [comment]
I am not sure I understand what you mean. But this seems a real edge case where the name of the requester is included in a publicly available document. In any case, automatic redactions can be undone by requesters, so I don't believe we should over-engineer for this case.

**Comment by alehaa** [comment]
Sorry for the missunderstanding.

An agency sent me a PDF 310 pages long, including several documents. The first pages are a letter including my name - which has to be redacted. The following pages include protocols from Bundestag listing all names participating in the debate. Now, as I need to redact the first pages, froide automatically searches the following 300+ pages for my name - which can't be undone, as the UI just allows one to either redact pages (including the automatically selected sections) or none of them.

Example:
1. Page: Dear ~Mr. John Doe~, […] (personal, name redacted)
2. Page: Speaking: James ~Doe~, Laura Smith, ~John~ Brown (public protocol)
  -> The 1. page was addressed to John Doe.

**Comment by stefanw** [comment]
Maybe it would help if the interface showed how many automatic redactions it did on how many pages?
The undo stack is per page and automatic redaction is one 'action' in the undo stack, so undoing automatic redaction per page is quite easy.

With 300+ pages not so much. Clearly an edge case, but splitting the document is the right solution here. For now you could  not publish the document and upload a split version in a 'fake postal reply'.

We know that automatic redaction can leak information, it can happen in the message text as well: Imagine a Herr Sehr: [redacted] geehrter Herr [redacted]. That's why you can undo redactions. It's not perfect, but without it would be worse. General rule: if your real name is too sensitive for the internet, don't use your real name.

**Comment by alehaa** [comment]
Honestly, that's the first time I realize one can undo redactions, including the automatic ones. As these kind of documents are pretty rare, I think the solution suggested by @stefanw should be sufficient.
