### ISSUE TITLE
Don't anonymize commenter if they did the FOI request non-anonymized

### ISSUE THREAD

**Issue by jfowl** [okfde/froide#539]
See:
https://fragdenstaat.de/anfrage/aufstellung-aller-durch-die-bundesanstalt-fur-immobilienaufgaben-verwalteten-liegenschaften/#nachricht-676501

![image](https://user-images.githubusercontent.com/15788906/157902432-18738dc5-d9ac-4cdc-aad6-15e41df4ed2b.png)

**Comment by pajowu** [comment]
Thank you for your suggestion. froide is the correct repo for this, so I moved the issue.

**Comment by pajowu** [comment]
After some internal discussion we decided that the proper fix is **not showing the badge**, instead of showing the name. The main reason for not showing the name was so it isn't indexed by search engines. Therefore still showing the badge is not really a huge issue[^1], but I agree that it is more consistent only either show none or both at the same time.

[^1]: At least not with the current level of website understanding search engines seem to have. Maybe in the future they will be able to connect this information at some point
