### ISSUE TITLE
Delete attachment - Feature proposal 

### ISSUE THREAD

**Issue by bebr43** [okfde/froide#733]
The uploader of an **attachment** should be facilitated to **delete** it, at least as long as it is unpublished. 

I stepped on this as I failed to use the black-out feature correctly - and decided to upload the scan again, assuming I could delete the former one.

**Comment by pajowu** [comment]
Hey, first of all thanks a lot for opening the issue.

We discussed this internally and since this does not happen too often, we decided to not implement this feature for now. However we are not opposed to discussing this again or merging a PR in case someone else wants to implement this.

Until then, attachments can be deleted by the admins of the froide instance. In the case of fragdenstaat.de, you can find the contact information at https://fragdenstaat.de/kontakt/
